#!/bin/sh

DIR=CaratInterface
PKGTAR=$DIR-2.3.10.tar

# remove old archive
rm -f $PKGTAR*

# update documentation
(cd .. && gap -A -q --quitonbreak -c 'Read("makedoc.g" : relativePath:="../../..");')

# make the package archive
mkdir -p $DIR
cd $DIR
  mkdir -p doc gap tst
  git clone https://github.com/lbfm-rwth/carat.git
  (cd carat && ./autogen.sh)
  tar zcf carat.tgz --exclude=carat/.git carat 
  rm -rf carat
cd ..
grep -v svg ../README.md > $DIR/README
cp -p ../*.g ../INSTALL ../Changelog ../GPL $DIR/
cp -p ../Makefile ../configure $DIR/
cp -p ../doc/*.xml ../doc/*.bib ../doc/*.css ../doc/*.js \
  ../doc/chap*.html ../doc/chap*.txt ../doc/chooser.html \
  ../doc/manual.lab ../doc/manual.six ../doc/manual.pdf $DIR/doc/
cp -p ../gap/*.g[di] $DIR/gap/
cp -p ../tst/*.g ../tst/*.tst  $DIR/tst/
chmod -R a+rX $DIR 
tar cvf $PKGTAR $DIR
chmod a+r $PKGTAR
gzip $PKGTAR

# cleanup
rm -rf $DIR
